//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAsyncService")]
    public interface IAsyncService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncService/Fun1")]
        void Fun1(string s1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncService/Fun1")]
        System.Threading.Tasks.Task Fun1Async(string s1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncService/Fun2", ReplyAction="http://tempuri.org/IAsyncService/Fun2Response")]
        void Fun2(string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncService/Fun2", ReplyAction="http://tempuri.org/IAsyncService/Fun2Response")]
        System.Threading.Tasks.Task Fun2Async(string s2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsyncServiceChannel : WcfServiceClient.ServiceReference1.IAsyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsyncServiceClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IAsyncService>, WcfServiceClient.ServiceReference1.IAsyncService {
        
        public AsyncServiceClient() {
        }
        
        public AsyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Fun1(string s1) {
            base.Channel.Fun1(s1);
        }
        
        public System.Threading.Tasks.Task Fun1Async(string s1) {
            return base.Channel.Fun1Async(s1);
        }
        
        public void Fun2(string s2) {
            base.Channel.Fun2(s2);
        }
        
        public System.Threading.Tasks.Task Fun2Async(string s2) {
            return base.Channel.Fun2Async(s2);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/addCNum", ReplyAction="http://tempuri.org/ICalculator/addCNumResponse")]
        WcfService2.ComplexNum addCNum(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/addCNum", ReplyAction="http://tempuri.org/ICalculator/addCNumResponse")]
        System.Threading.Tasks.Task<WcfService2.ComplexNum> addCNumAsync(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/multCNum", ReplyAction="http://tempuri.org/ICalculator/multCNumResponse")]
        WcfService2.ComplexNum multCNum(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/multCNum", ReplyAction="http://tempuri.org/ICalculator/multCNumResponse")]
        System.Threading.Tasks.Task<WcfService2.ComplexNum> multCNumAsync(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/divCNum", ReplyAction="http://tempuri.org/ICalculator/divCNumResponse")]
        WcfService2.ComplexNum divCNum(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/divCNum", ReplyAction="http://tempuri.org/ICalculator/divCNumResponse")]
        System.Threading.Tasks.Task<WcfService2.ComplexNum> divCNumAsync(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : WcfServiceClient.ServiceReference1.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.ICalculator>, WcfServiceClient.ServiceReference1.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService2.ComplexNum addCNum(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2) {
            return base.Channel.addCNum(n1, n2);
        }
        
        public System.Threading.Tasks.Task<WcfService2.ComplexNum> addCNumAsync(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2) {
            return base.Channel.addCNumAsync(n1, n2);
        }
        
        public WcfService2.ComplexNum multCNum(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2) {
            return base.Channel.multCNum(n1, n2);
        }
        
        public System.Threading.Tasks.Task<WcfService2.ComplexNum> multCNumAsync(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2) {
            return base.Channel.multCNumAsync(n1, n2);
        }
        
        public WcfService2.ComplexNum divCNum(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2) {
            return base.Channel.divCNum(n1, n2);
        }
        
        public System.Threading.Tasks.Task<WcfService2.ComplexNum> divCNumAsync(WcfService2.ComplexNum n1, WcfService2.ComplexNum n2) {
            return base.Channel.divCNumAsync(n1, n2);
        }
    }
}
